package br.com.guerravpn.crediflow;
import android.app.AlertDialog;
import android.text.InputType;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.Locale;
final class AdminUi {
private final MainActivityV06 a; private final Ui u;
AdminUi(MainActivityV06 activity){a=activity;u=activity.u;}
void show(){
LinearLayout root=u.page();u.eyebrow(root,"ADMINISTRAÇÃO");u.title(root,"Painel Admin",33);u.body(root,"Análise manual de cadastros, limites, taxas e solicitações de empréstimo.");

LinearLayout summary=u.card();u.cardTitle(summary,"Resumo");TextView summaryLoading=u.body(summary,"Carregando pendências e ativos...");root.addView(summary);

LinearLayout actions=u.card();u.cardTitle(actions,"Operação");Button loansButton=u.primary("Solicitações de empréstimo",v->showLoans());actions.addView(loansButton);actions.addView(u.outline("Atualizar cadastros",v->show()));actions.addView(u.outline("Sair do Admin",v->a.logout()));root.addView(actions);
LinearLayout info=u.card();u.cardTitle(info,"Regra da análise");u.body(info,"O Admin consulta os dados e define manualmente limite, risco, juros, parcelas, multa e juros de atraso. O aplicativo não toma sozinho a decisão de crédito.");root.addView(info);
u.title(root,"Análises",26);LinearLayout list=u.card();TextView loading=u.body(list,"Carregando cadastros...");root.addView(list);

a.io.execute(()->{try{
String path="/rest/v1/credit_applications?select=id,status,email,full_name,phone,monthly_income,approved_limit,approved_risk_tier,approved_monthly_rate,approved_max_installments,approved_late_interest_daily_rate,approved_late_fee_rate,created_at&order=created_at.desc&limit=500";
Api.Resp response=Api.get(path,a.accessToken);if(!response.ok())throw new Exception(response.errorMessage());JSONArray items=response.array();
int reviewCount=0,activeFromApps=0;for(int i=0;i<items.length();i++){JSONObject app=items.optJSONObject(i);if(app==null)continue;String st=app.optString("status");if("under_review".equals(st)||"correction_required".equals(st))reviewCount++;if("active".equals(st))activeFromApps++;}
int pendingLoans=-1,activeLoans=-1;try{Api.Resp loanResponse=Api.get("/rest/v1/loans?select=id,status&limit=1000",a.accessToken);if(loanResponse.ok()){JSONArray loans=loanResponse.array();pendingLoans=0;activeLoans=0;for(int i=0;i<loans.length();i++){JSONObject loan=loans.optJSONObject(i);if(loan==null)continue;String st=loan.optString("status");if("requested".equals(st))pendingLoans++;if("active".equals(st)||"late".equals(st))activeLoans++;}}}catch(Exception ignored){}
int activeAccounts=activeFromApps;try{Api.Resp profiles=Api.get("/rest/v1/profiles?select=user_id,account_status&account_status=eq.active&limit=1000",a.accessToken);if(profiles.ok())activeAccounts=profiles.array().length();}catch(Exception ignored){}
final int fReview=reviewCount,fPending=pendingLoans,fActiveLoans=activeLoans,fActiveAccounts=activeAccounts;
a.runOnUiThread(()->{summary.removeView(summaryLoading);u.stat(summary,"Solicitações pendentes",fPending<0?"—":String.valueOf(fPending));u.stat(summary,"Empréstimos ativos",fActiveLoans<0?"—":String.valueOf(fActiveLoans));u.stat(summary,"Contas ativas",String.valueOf(fActiveAccounts));u.stat(summary,"Cadastros em análise",String.valueOf(fReview));if(fPending>0){summary.addView(u.badge(fPending+" solicitação"+(fPending==1?" pendente":" pendentes"),Ui.AMBER));loansButton.setText("Solicitações de empréstimo · "+fPending+" pendente"+(fPending==1?"":"s"));}else if(fPending==0){loansButton.setText("Solicitações de empréstimo · 0 pendentes");}renderApplications(list,loading,items);});
}catch(Exception ex){a.runOnUiThread(()->{summaryLoading.setText("Não foi possível atualizar o resumo.");loading.setText(MainActivityV06.friendly(ex));});}});
}
private void renderApplications(LinearLayout list,TextView loading,JSONArray items){list.removeView(loading);if(items.length()==0){u.body(list,"Nenhum cadastro recebido.");return;}for(int i=0;i<items.length();i++){JSONObject app=items.optJSONObject(i);if(app==null)continue;LinearLayout card=u.mini();u.cardTitle(card,app.optString("full_name","Cliente"));u.body(card,app.optString("email",""));card.addView(u.badge(MainActivityV06.statusPt(app.optString("status")),MainActivityV06.statusColor(app.optString("status"))));if(!app.isNull("monthly_income"))u.stat(card,"Renda informada",MainActivityV06.money(app.optDouble("monthly_income",0)));if(!app.isNull("approved_limit"))u.stat(card,"Limite",MainActivityV06.money(app.optDouble("approved_limit",0)));card.addView(u.outline("Abrir análise",v->showApplication(app)));list.addView(card);}}
private void showApplication(JSONObject app){
LinearLayout root=u.page();u.back(root,this::show);u.eyebrow(root,"ANÁLISE MANUAL");u.title(root,app.optString("full_name","Cliente"),29);u.body(root,app.optString("email","")+" · "+app.optString("phone",""));String appStatus=app.optString("status");root.addView(u.badge(MainActivityV06.statusPt(appStatus),MainActivityV06.statusColor(appStatus)));
LinearLayout current=u.card();u.cardTitle(current,"Dados da solicitação");if(!app.isNull("monthly_income"))u.stat(current,"Renda mensal",MainActivityV06.money(app.optDouble("monthly_income",0)));u.stat(current,"Cadastro",app.optString("created_at","").replace('T',' '));root.addView(current);
LinearLayout policy=u.card();u.cardTitle(policy,"Condições aprovadas");EditText limit=u.input("Limite aprovado · R$",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText risk=u.input("Faixa de risco · ex.: baixo",InputType.TYPE_CLASS_TEXT);EditText monthly=u.input("Juros ao mês · %",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText maxInstallments=u.input("Máximo de parcelas",InputType.TYPE_CLASS_NUMBER);EditText lateDaily=u.input("Juros de atraso ao dia · %",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText lateFee=u.input("Multa por atraso · %",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText notes=u.input("Observação da análise",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);
if(!app.isNull("approved_limit"))limit.setText(decimal(app.optDouble("approved_limit",0)));risk.setText(app.optString("approved_risk_tier","baixo"));if(!app.isNull("approved_monthly_rate"))monthly.setText(decimal(app.optDouble("approved_monthly_rate",0)*100));if(!app.isNull("approved_max_installments"))maxInstallments.setText(String.valueOf(app.optInt("approved_max_installments",1)));if(!app.isNull("approved_late_interest_daily_rate"))lateDaily.setText(decimal(app.optDouble("approved_late_interest_daily_rate",0)*100));if(!app.isNull("approved_late_fee_rate"))lateFee.setText(decimal(app.optDouble("approved_late_fee_rate",0)*100));
boolean updating="approved".equals(appStatus)||"activation_sent".equals(appStatus)||"active".equals(appStatus);policy.addView(limit);policy.addView(risk);policy.addView(monthly);policy.addView(maxInstallments);policy.addView(lateDaily);policy.addView(lateFee);policy.addView(notes);TextView error=u.error();policy.addView(error);Button approve=u.primary(updating?"Atualizar condições":"Aprovar cadastro",null);Button reject=u.outline("Rejeitar cadastro",null);policy.addView(approve);if(!"active".equals(appStatus)&&!"activation_sent".equals(appStatus))policy.addView(reject);if("approved".equals(appStatus)||"activation_sent".equals(appStatus)){Button activation=u.primary("Enviar código de ativação por e-mail",null);policy.addView(activation);activation.setOnClickListener(v->sendActivation(app,activation,error));}root.addView(policy);
approve.setOnClickListener(v->{try{JSONObject body=new JSONObject();body.put("applicationId",app.optString("id"));body.put("decision","approved");body.put("approvedLimit",parse(limit));body.put("riskTier",risk.getText().toString().trim());body.put("monthlyRate",parse(monthly)/100d);body.put("maxInstallments",Integer.parseInt(maxInstallments.getText().toString().trim()));body.put("lateInterestDailyRate",parse(lateDaily)/100d);body.put("lateFeeRate",parse(lateFee)/100d);body.put("notes",notes.getText().toString().trim());review(body,approve,error,updating);}catch(Exception ex){error.setText("Confira limite, taxas e número de parcelas.");}});
reject.setOnClickListener(v->{try{JSONObject body=new JSONObject();body.put("applicationId",app.optString("id"));body.put("decision","rejected");body.put("notes",notes.getText().toString().trim());review(body,reject,error,false);}catch(Exception ex){error.setText("Não foi possível montar a decisão.");}});
}
private void review(JSONObject body,Button button,TextView error,boolean updating){String normal=button.getText().toString();a.busy(button,true,"Salvando...");a.io.execute(()->{try{Api.Resp response=Api.adminRecordReview(a.accessToken,body);if(!response.ok())throw new Exception(response.errorMessage());a.runOnUiThread(()->{a.busy(button,false,normal);boolean approved=body.optString("decision").equals("approved");new AlertDialog.Builder(a).setTitle(updating&&approved?"Condições atualizadas":"Análise registrada").setMessage(approved?(updating?"Limite, juros, parcelas e encargos foram atualizados. Se a conta já estiver ativa, as novas condições já valem no limite do cliente.":"Cadastro aprovado. Agora você pode enviar o código de ativação."):"Cadastro rejeitado.").setPositiveButton("OK",(d,w)->show()).show();});}catch(Exception ex){a.runOnUiThread(()->{a.busy(button,false,normal);error.setText(MainActivityV06.friendly(ex));});}});}
private void sendActivation(JSONObject app,Button button,TextView error){a.busy(button,true,"Enviando e-mail...");a.io.execute(()->{try{Api.Resp response=Api.adminSendActivation(a.accessToken,app.optString("id"));if(!response.ok())throw new Exception(response.errorMessage());a.runOnUiThread(()->{a.busy(button,false,"Enviar código de ativação por e-mail");new AlertDialog.Builder(a).setTitle("Código enviado").setMessage("O código de ativação foi enviado para "+app.optString("email","o cliente")+".").setPositiveButton("OK",null).show();});}catch(Exception ex){a.runOnUiThread(()->{a.busy(button,false,"Enviar código de ativação por e-mail");error.setText(MainActivityV06.friendly(ex));});}});}
void showLoans(){LinearLayout root=u.page();u.back(root,this::show);u.eyebrow(root,"EMPRÉSTIMOS");u.title(root,"Solicitações",31);u.body(root,"Confira o contrato e a chave Pix antes de confirmar que o valor foi enviado.");LinearLayout list=u.card();TextView loading=u.body(list,"Carregando solicitações...");root.addView(list);a.io.execute(()->{try{Api.Resp response=Api.adminLoanRequests(a.accessToken);if(!response.ok())throw new Exception(response.errorMessage());JSONArray items=response.object().optJSONArray("items");if(items==null)items=new JSONArray();JSONArray finalItems=items;a.runOnUiThread(()->renderLoans(list,loading,finalItems));}catch(Exception ex){a.runOnUiThread(()->loading.setText(MainActivityV06.friendly(ex)));}});}
private void renderLoans(LinearLayout list,TextView loading,JSONArray items){list.removeView(loading);if(items.length()==0){u.body(list,"Nenhuma solicitação de empréstimo.");return;}for(int i=0;i<items.length();i++){JSONObject loan=items.optJSONObject(i);if(loan==null)continue;JSONObject profile=loan.optJSONObject("profile"),pix=loan.optJSONObject("pix"),contract=loan.optJSONObject("contract");LinearLayout card=u.mini();u.cardTitle(card,profile==null?"Cliente":profile.optString("full_name","Cliente"));card.addView(u.badge(MainActivityV06.statusPt(loan.optString("status")),MainActivityV06.statusColor(loan.optString("status"))));u.stat(card,"Solicitado",MainActivityV06.money(loan.optDouble("principal",0)));u.stat(card,"Juros",MainActivityV06.money(loan.optDouble("interest_amount",0)));u.stat(card,"Total",MainActivityV06.money(loan.optDouble("total_amount",0)));u.stat(card,"Parcelas",loan.optInt("installments_count",1)+"x");u.stat(card,"1º vencimento",loan.optString("first_due_date","-"));if(pix!=null)u.stat(card,"Pix",pix.optString("key_type","")+" · "+pix.optString("key_value",pix.optString("key_masked","")));if(contract!=null)u.stat(card,"Contrato",contract.optString("contract_number","-"));card.addView(u.outline("Ver detalhes",v->showLoan(loan)));list.addView(card);}}
private void showLoan(JSONObject loan){LinearLayout root=u.page();u.back(root,this::showLoans);JSONObject profile=loan.optJSONObject("profile"),pix=loan.optJSONObject("pix"),contract=loan.optJSONObject("contract");u.eyebrow(root,"SOLICITAÇÃO DE CRÉDITO");u.title(root,profile==null?"Cliente":profile.optString("full_name","Cliente"),29);if(profile!=null)u.body(root,profile.optString("email","")+" · "+profile.optString("phone",""));root.addView(u.badge(MainActivityV06.statusPt(loan.optString("status")),MainActivityV06.statusColor(loan.optString("status"))));LinearLayout details=u.card();u.cardTitle(details,"Condições");u.stat(details,"Valor",MainActivityV06.money(loan.optDouble("principal",0)));u.stat(details,"Taxa mensal",MainActivityV06.percent(loan.optDouble("monthly_interest_rate",0)));u.stat(details,"Juros",MainActivityV06.money(loan.optDouble("interest_amount",0)));u.stat(details,"Total",MainActivityV06.money(loan.optDouble("total_amount",0)));u.stat(details,"Parcelas",String.valueOf(loan.optInt("installments_count",1)));u.stat(details,"Primeiro vencimento",loan.optString("first_due_date","-"));u.stat(details,"Juros atraso/dia",String.format(new Locale("pt","BR"),"%.4f%%",loan.optDouble("late_interest_daily_rate",0)*100));u.stat(details,"Multa atraso",MainActivityV06.percent(loan.optDouble("late_fee_rate",0)));root.addView(details);
LinearLayout payment=u.card();u.cardTitle(payment,"Liberação por Pix");if(pix!=null){u.stat(payment,"Tipo",pix.optString("key_type","-"));u.stat(payment,"Chave",pix.optString("key_value",pix.optString("key_masked","-")));if(!pix.optString("holder_name","").isEmpty())u.stat(payment,"Titular",pix.optString("holder_name"));if(!pix.optString("institution_name","").isEmpty())u.stat(payment,"Instituição",pix.optString("institution_name"));}else u.body(payment,"Chave Pix não encontrada.");if(contract!=null)u.stat(payment,"Contrato",contract.optString("contract_number","-"));EditText note=u.input("Observação da transferência",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);payment.addView(note);TextView error=u.error();payment.addView(error);if("requested".equals(loan.optString("status"))){Button confirm=u.primary("Confirmar Pix enviado",null),reject=u.outline("Rejeitar solicitação",null);payment.addView(confirm);payment.addView(reject);confirm.setOnClickListener(v->confirmLoan(loan,note,confirm,error));reject.setOnClickListener(v->rejectLoan(loan,note,reject,error));}root.addView(payment);
JSONArray installments=loan.optJSONArray("installments");if(installments!=null&&installments.length()>0){LinearLayout schedule=u.card();u.cardTitle(schedule,"Parcelas geradas");for(int i=0;i<installments.length();i++){JSONObject it=installments.optJSONObject(i);if(it==null)continue;u.stat(schedule,"#"+it.optInt("installment_number")+" · "+it.optString("due_date"),MainActivityV06.money(it.optDouble("amount_due",0))+" · "+MainActivityV06.statusPt(it.optString("status")));}root.addView(schedule);}}
private void confirmLoan(JSONObject loan,EditText note,Button button,TextView error){new AlertDialog.Builder(a).setTitle("Confirmar liberação").setMessage("Confirme somente depois de enviar o Pix para a chave exibida. Isso ativará o empréstimo e gerará as parcelas.").setNegativeButton("Cancelar",null).setPositiveButton("Confirmar",(d,w)->{a.busy(button,true,"Confirmando...");a.io.execute(()->{try{Api.Resp response=Api.adminConfirmDisbursement(a.accessToken,loan.optString("id"),note.getText().toString().trim());if(!response.ok())throw new Exception(response.errorMessage());a.runOnUiThread(this::showLoans);}catch(Exception ex){a.runOnUiThread(()->{a.busy(button,false,"Confirmar Pix enviado");error.setText(MainActivityV06.friendly(ex));});}});}).show();}
private void rejectLoan(JSONObject loan,EditText note,Button button,TextView error){a.busy(button,true,"Rejeitando...");a.io.execute(()->{try{Api.Resp response=Api.adminRejectLoan(a.accessToken,loan.optString("id"),note.getText().toString().trim());if(!response.ok())throw new Exception(response.errorMessage());a.runOnUiThread(this::showLoans);}catch(Exception ex){a.runOnUiThread(()->{a.busy(button,false,"Rejeitar solicitação");error.setText(MainActivityV06.friendly(ex));});}});}
private static double parse(EditText e){return Double.parseDouble(e.getText().toString().trim().replace(',','.'));}
private static String decimal(double value){if(Math.rint(value)==value)return String.format(Locale.US,"%.0f",value);return String.format(Locale.US,"%.4f",value).replaceAll("0+$","").replaceAll("\\.$","");}
}
